### ISSUE TITLE
Part-Time Jobs

### ISSUE THREAD

**Issue by Gaonuk** [cspuc/jobs#1]
Envola podrias hacer una seccion de trabajos part-time en donde tal vez acepten estudiantes, o podrias agregar un tag "estudiantes" a aquellos trabajos que acepten a estudiantes

**Comment by nbcl** [comment]
Gracias por la sugerencia @Gaonuk! 

Actualmente el tag `no-exp` cumple esa función.

> `no-exp` : No se requiere experiencia o se puede postular siendo alumno.
